server:
  port: 8081


dubbo:
  consumer:
    timeout: 60000
    retries: 0
    check: false
  protocol:
    port: 31111
    name: dubbo
  registry:
    address: zookeeper://10.4.86.9:2181
    id: etc-highway-tdg
  application:
    name: etc-highway-tdg